---
title: "CLASS analysis"
author: "BVD"
date: "4/11/2019"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
load("~/pb_data")
load("~/all_class")
library(ltm)
#library(GPArotation)
library(itemanalysis)
library(psych)
library(tidyr)
library("ggplot2")
library(gvlma)
library("HLMdiag")
library("DHARMa")
library("car") #for the Levene test which we will not discuss here
library("Matrix")
library(mitools)
library(stargazer)
library(lme4)
library(nlme)
library(mice)
library(mitml)
library(multcomp)
library(foreach)
library(ggplot2)
library(stringr)
library(dplyr)  #I load dplyr last because some of its functions (select) will be masked by plyr and it is a PITA to debug
library(kableExtra)
plot_col <- c('#66c2a5', '#fc8d62', '#8da0cb')
#cbbpalette <- c('#000000','#E69F00','#56B4E9')
cbbpalette <- c( "#009E73", "#e79f00", "#9ad0f3", "#0072B2", "#D55E00", 
    "#CC79A7","#000000", "#F0E442") #colorblind and grayscale friendly.
```

Combine data

```{r}
pre_data <- as.data.frame(pb_data[c(2:4,6:7,9,11:31,33,35:41,43)], drop=false)
post_data <- as.data.frame(pb_data[c(46:48,50:51,53,55:75,77,79:85,87)], drop=false)
names(pre_data) <- c("q1","q2","q3","q5","q6","q8","q10","q11","q12","q13","q14","q15","q16","q17","q18","q19","q20","q21","q22","q23","q24","q25","q26","q27","q28","q29","q30","q32","q34","q35","q36","q37","q38","q39","q40","q42")
names(post_data) <- c("q1","q2","q3","q5","q6","q8","q10","q11","q12","q13","q14","q15","q16","q17","q18","q19","q20","q21","q22","q23","q24","q25","q26","q27","q28","q29","q30","q32","q34","q35","q36","q37","q38","q39","q40","q42")
all_data <- rbind(pre_data,post_data)
all_data = all_data[complete.cases(all_data),]
red_set <- c("q3","q5","q14","q21","q22","q23","q24","q25","q28","q29","q30","q32","q34","q37","q40")
red_data = all_data[red_set]
red_pre_data = pre_data[red_set]
red_post_data = post_data[red_set]
red_pre_data = red_pre_data[complete.cases(red_pre_data),]
red_post_data = red_post_data[complete.cases(red_post_data),]
```

Item analysis all items
```{r}
item.analysis_all <- itemanalysis2(data=all_data,options=c(1,2,3,4,5),ngroup=37,correction=TRUE)
pbserial <- as.data.frame(item.analysis_all[["plots"]][[1]][["plot_env"]][["dist.disc"]])
names(pbserial) <- c("SD","D","N","A","SA")
pbserial$SD_D <- pbserial$D-pbserial$SD
pbserial$D_N <- pbserial$N-pbserial$D
pbserial$N_A <- pbserial$A-pbserial$N
pbserial$A_SA <- pbserial$SA-pbserial$A
dstat <- pbserial %>% summarise_all(funs(mean, sd))
#item.analysis_all$plots[[1]] #these are interesting. Similar to item difficulty plots
```

Item analysis reduced items
```{r}
item.analysis_red <- itemanalysis2(data=red_data,options=c(1,2,3,4,5),ngroup=16,correction=TRUE)
freq_red <- as.data.frame(item.analysis_red[["plots"]][[1]][["plot_env"]][["dist.sel"]])
names(freq_red) <- c("SD","D","N","A","SA")
mean_freq_red <- freq_red %>% summarise_all(funs(mean, sd))
pbserial_red <- as.data.frame(item.analysis_red[["plots"]][[1]][["plot_env"]][["dist.disc"]])
names(pbserial_red) <- c("SD","D","N","A","SA")
pbserial_red$SD_D <- pbserial_red$D-pbserial_red$SD
pbserial_red$D_N <- pbserial_red$N-pbserial_red$D
pbserial_red$N_A <- pbserial_red$A-pbserial_red$N
pbserial_red$A_SA <- pbserial_red$SA-pbserial_red$A
pbserial_red_shift <- pbserial_red[c("SD_D","D_N","N_A","A_SA")]
dstat_red <- pbserial_red %>% summarise_all(funs(mean, sd))
#item.analysis_all$plots[[1]] #these are interesting. Similar to item difficulty plots
```

Alt scoring analysis
```{r}
all_data_alt <- all_data
all_data_alt[all_data_alt==2] <- 1
all_data_alt[all_data_alt==3] <- 1
all_data_alt[all_data_alt==4] <- 2
all_data_alt[all_data_alt==5] <- 3
item.analysis_alt <- itemanalysis2(data=all_data_alt, options=c(1,2,3),ngroup=37,correction=TRUE)
pbserial_alt <- as.data.frame(item.analysis_alt[["plots"]][[1]][["plot_env"]][["dist.disc"]])
names(pbserial_alt) <- c("SDN","A","SA")
pbserial_alt$N_A <- pbserial_alt$A-pbserial_alt$SDN
pbserial_alt$A_SA <- pbserial_alt$SA-pbserial_alt$A
dstat_alt <- pbserial_alt %>% summarise_all(funs(mean, sd))

red_pre_data_alt <- red_pre_data
red_pre_data_alt[red_pre_data_alt==2] <- 1
red_pre_data_alt[red_pre_data_alt==3] <- 1
red_pre_data_alt[red_pre_data_alt==4] <- 2
red_pre_data_alt[red_pre_data_alt==5] <- 3
rmean_pre_alt <- as.data.frame(rowMeans(red_pre_data_alt, na.rm = FALSE, dims = 1)/3)
dist_stat_pre_alt <- rmean_pre_alt %>% summarise_all(funs(mean, sd))

red_post_data_alt <- red_post_data
red_post_data_alt[red_post_data_alt==2] <- 1
red_post_data_alt[red_post_data_alt==3] <- 1
red_post_data_alt[red_post_data_alt==4] <- 2
red_post_data_alt[red_post_data_alt==5] <- 3
rmean_post_alt <- as.data.frame(rowMeans(red_post_data_alt, na.rm = FALSE, dims = 1)/3)
dist_stat_post_alt <- rmean_post_alt %>% summarise_all(funs(mean, sd))
```

plot point-biserials
```{r}
multi.hist(pbserial,xlim=c(-0.5,0.5))
multi.hist(pbserial_red,xlim=c(-0.5,0.5))
multi.hist(pbserial_red_shift,xlim=c(-0.5,0.5))
```

score distributions
```{r}
dist_cc <- pb_data[c("l_pre","e_pre","l_post","e_post")]
dist_cc = dist_cc[complete.cases(dist_cc),]

dist_pre <- pb_data[c("l_pre","e_pre","")]
dist_pre = dist_pre[complete.cases(dist_pre),]
dist_post <- pb_data[c("l_post","e_post")]
dist_post = dist_post[complete.cases(dist_post),]
dist_stat_cc <- dist_cc %>% summarise_all(funs(mean, sd))
dist_stat_pre <- dist_pre %>% summarise_all(funs(mean, sd))
dist_stat_post <- dist_post %>% summarise_all(funs(mean, sd))

co_l <- (dist_stat_post$l_post_mean-dist_stat_pre$l_pre_mean)/((((5393)*((dist_stat_post$l_post_sd)^2)+(7841)*(dist_stat_pre$l_pre_sd)^2)/(5393+7841))^0.5)
co_e <- (dist_stat_post$e_post_mean-dist_stat_pre$e_pre_mean)/((((5393)*(dist_stat_post$e_post_sd)^2+(7841)*(dist_stat_pre$e_pre_sd)^2)/(5393+7841))^0.5)
co_alt <- (dist_stat_post_alt$mean-dist_stat_pre_alt$mean)/((((5393)*(dist_stat_post_alt$sd)^2+(7841)*(dist_stat_pre_alt$sd)^2)/(5393+7841))^0.5)
#cohen_l <- cohen.d(dist_pre$l_pre,dist_post$l_post)

multi.hist(dist_plots,xlim=c(0,100))
all_data = all_data[complete.cases(all_data),]
dist_stat <- dist_plots %>% summarise_all(funs(mean, sd))

```

Density plot - point-biserial
```{r}
pbserial_red_forplot <- pbserial_red[c(1:5)]
forplot <- gather(pbserial_red_forplot,key="key",value="value")
forplot$key <- factor(forplot$key, levels = c("SD", "D", "N", "A","SA"))

ggplot(data=forplot,aes(x=value,fill=key))+geom_density(alpha=0.5) + 
  ylab("Density") + xlab("Point-biserial Correlation") +  
  xlim(c(-0.5,0.5)) +
  theme(legend.position = c(0.1,0.8), legend.title = element_blank(),
        legend.text.align = 0, panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=10, color = "black")) +
  scale_fill_manual(breaks= c("SD", "D", "N", "A","SA"),
                     labels = c(expression(italic(" SD")), expression(italic(" D")), 
                                expression(italic(" N")), expression(italic(" A")), 
                                expression(italic(" SA"))),
                     values=cbbpalette)
ggsave("dist.png", plot= last_plot(), dpi=300, width = 3.5, height = 3.25, units = "in", device = "png")
```

Density plot - use
```{r}
forfreqplot <- gather(freq_red,key="key",value="value")
forfreqplot$key <- factor(forplot$key, levels = c("SD", "D", "N", "A","SA"))

ggplot(data=forfreqplot,aes(x=value,fill=key))+geom_density(alpha=0.5) + 
  ylab("Density") + xlab("Frequency of Use") +  
  xlim(c(0.0,0.6)) +
  theme(legend.position = c(0.8,0.8), legend.title = element_blank(),
        legend.text.align = 0, panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=10, color = "black")) +
  scale_fill_manual(breaks= c("SD", "D", "N", "A","SA"),
                     labels = c(expression(italic(" SD")), expression(italic(" D")), 
                                expression(italic(" N")), expression(italic(" A")), 
                                expression(italic(" SA"))),
                     values=cbbpalette)
ggsave("distfreq.png", plot= last_plot(), dpi=300, width = 3.5, height = 3.25, units = "in", device = "png")
```

factor analysis
```{r}
parallel <- fa.parallel(all_data, fm = 'minres', fa = 'fa')

onefactor <- fa(all_data,nfactors = 1,rotate = "oblimin",fm="minres")
print(onefactor)
print(onefactor$loadings,cutoff = 0.4)

twofactor <- fa(all_data,nfactors = 2,rotate = "oblimin",fm="minres") #Looks like the best most simple model (variance explained and questions maintained)
print(twofactor)
print(twofactor$loadings,cutoff = 0.4)

threefactor <- fa(all_data,nfactors = 3,rotate = "oblimin",fm="minres")
print(threefactor)
print(threefactor$loadings,cutoff = 0.4)

fourfactor <- fa(all_data,nfactors = 4,rotate = "oblimin",fm="minres")
print(fourfactor)
print(fourfactor$loadings,cutoff = 0.4)

fivefactor <- fa(all_data,nfactors = 5,rotate = "oblimin",fm="minres")
print(fivefactor)
print(fivefactor$loadings,cutoff = 0.4)

fa.diagram(onefactor)
fa.diagram(twofactor)
fa.diagram(threefactor)
fa.diagram(fourfactor)
```
