---
title: "CLASS PERC 2019"
author: "Jayson Nissen"
date: "5/9/2019"
output: html_document
---
HLM Analysis
```{r message=FALSE, warning=FALSE}
#load("~/hmi_data_1_10_19")
#load("~/Physics_Equity/hmifall2018_m10_better")
#load("~/Documents/LA Postdoc stuff copy/RData/LASSO/Denver-Chico_collaboration/Physics_Equity_new/hmifall2018_m10_better")
#load("hmi_4_21_19")
load("~/Documents/LA Postdoc stuff copy/RData/LASSO/Denver-Chico_collaboration/CLASS Analysis/hmi_4_21_19")
library(tidyr)
library("ggplot2")
library(gvlma)
library("HLMdiag")
library("DHARMa")
library("car") #for the Levene test which we will not discuss here
library("Matrix")
library(mitools)
library(stargazer)
library(lme4)
library(nlme)
library(mice)
library(mitml)
library(multcomp)
library(foreach)
library(ggplot2)
library(stringr)
library(dplyr)  #I load dplyr last because some of its functions (select) will be masked by plyr and it is a PITA to debug
library(kableExtra)
plot_col <- c('#66c2a5', '#fc8d62', '#8da0cb')
#cbbpalette <- c('#000000','#E69F00','#56B4E9')
cbbpalette <- c( "#009E73", "#e79f00", "#9ad0f3", "#0072B2", "#D55E00", 
    "#CC79A7","#000000", "#F0E442") #colorblind and grayscale friendly.
```

Creating mitml and extra variables
```{r}
#df_full <- complete(hmi.fall.2018)
#str(df_full)
MIdata<-mids2mitml.list(hmi_4_19_19) #converts file type
thing <- list()
for (i in 1:10){
  temp <- MIdata[[i]]
  temp <- temp[temp$level!=2 & temp$math=="calculus",]
  #temp <- temp[temp$course_id!="531",] # This is a small course that is throwing off the class means -- outlier
  class_means <- temp %>% group_by(course_id) %>% summarise(pre_mean_class = mean(e_pre))
  class_means$class_pre_cent <- class_means$pre_mean_class - mean(class_means$pre_mean_class)
  temp <- left_join(temp,class_means, by="course_id")
  temp$stud_pre_cent <- temp$e_pre - temp$pre_mean_class
  temp$gain <- temp$e_post - temp$e_pre
  temp$course_type <- ifelse(temp$math=="algebra" & temp$level=="1","algmech",ifelse(temp$math=="calculus" & temp$level=="1","calcmech",ifelse(temp$math=="algebra" & temp$level=="2","algenm",ifelse(temp$math=="calculus" & temp$level=="2","calcenm","other"))))
  #temp$coll <- ifelse(temp$lecture %in% 1,0,1)
  temp$retake <- ifelse(temp$first_time==1,0,1)
  #temp$race_otherstar_no_int[temp$amind_no_int %in% 1] <- 1 # combines the american indian students in to the other group there were 61 if these students
  temp$female <- ifelse(temp$male==1,0,1)
  thing[[i]] <- temp
  }
MIdata <- as.mitml.list(thing)
  
#as_courses <- unique(temp$course_id)
#save(as_courses, file="as_courses")

```

#Descriptive statistics by lecture and gender
```{r}
#variables: M, group by

desc2 <- foreach(i=1:10, .combine=rbind) %do% {
temp <- MIdata[[i]]
temp$race <- ifelse(temp$black_no_int ==1, "Black",ifelse(temp$hispanic_no_int ==1, "Hispanic",ifelse(temp$asian_no_int ==1, "Asian",ifelse(temp$pacisland_no_int ==1, "Island",ifelse(temp$race_otherstar_no_int ==1, "Other","White")))))
desc <- temp %>% group_by(collab_learning_during_class, male) %>% summarise(N = length(e_pre),
                                                                 pre_mean = mean(e_pre),
                                                                 pre_sd = sd(e_pre),
                                                                 post_mean = mean(e_post),
                                                                 post_sd = sd(e_post),
                                                                 gain_mean = mean (e_post-e_pre),
                                                                 gain_sd = sd(e_post-e_pre)
                                                                 )


return <- desc
}
desc <- desc2 %>% group_by(collab_learning_during_class, male) %>% summarise_all(funs(mean))
desc$collab_learning_during_class <- ifelse(desc$collab_learning_during_class == 0, "Lecture","Collaborative")
desc$male <- ifelse(desc$male==0, "Female","Male")
kable(desc, digits=1)
```

```{r}
e_pre1 <- with(MIdata,{lmer(e_pre~1 + (1|course_id))})
aic.1 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1 + (1|course_id))
  return <- AIC(mod_aic)
}

e_pre2 <- with(MIdata,{lmer(e_pre~1  + (1|course_id))})
aic.2 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1 + (1|course_id))
  return <- AIC(mod_aic)
}

e_pre3 <- with(MIdata,{lmer(e_pre~1  + female + (1|course_id))})
aic.3 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1  + female + (1|course_id))
  return <- AIC(mod_aic)
}

e_pre4 <- with(MIdata,{lmer(e_pre~1  + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))})
aic.4 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1 + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}


e_pre5 <- with(MIdata,{lmer(e_pre~1  + collab_learning_during_class +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))})
aic.5 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1  + collab_learning_during_class +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}

e_pre6 <- with(MIdata,{lmer(e_pre~1  +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))})
aic.6 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1 +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}

e_pre7 <- with(MIdata,{lmer(e_pre~1  + female*(asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) + (1|course_id) )})
aic.7 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_pre~1  + collab_learning_during_class +  female*(asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}

info_crit <- as.data.frame(cbind(aic.1,aic.2,aic.3,aic.4,aic.5,aic.6,aic.7))
#info_crit[11,] <- colMeans(info_crit)

colnames(info_crit) <- c("aic.1", "aic.2","aic.3","aic.4","aic.5","aic.6","aic.7")

ics <- as.data.frame(colMeans(info_crit))
ics$delta <- ics$`colMeans(info_crit)`- min(ics$`colMeans(info_crit)`)

barplot(ics$delta)

testEstimates(e_pre1, var.comp=TRUE)
testEstimates(e_pre2, var.comp=TRUE)
testEstimates(e_pre3, var.comp=TRUE)
testEstimates(e_pre4, var.comp=TRUE)
testEstimates(e_pre5, var.comp=TRUE) 
testEstimates(e_pre6, var.comp=TRUE)
testEstimates(e_pre7, var.comp=TRUE)
```

```{r}
pool_and_cov_diffwm <- function(x,y){
  get.est <- foreach(i=1:10, .combine=rbind) %do% {
  sxp3 <- summary(glht(x[[i]], linfct=y)) #specifically for post3
  covp3 <- vcov(glht(x[[i]], linfct=y))
  data.frame(imp=i, 
             group=rownames(sxp3$linfct),
             d = sxp3$test$coefficients, 
             var.d = (sxp3$test$sigma)^2,
             cov = covp3)
}
p3est <- get.est %>% group_by(group) %>% 
                  summarise(Q = mean(d), 
                            U = mean(var.d), 
                            B = var(d), 
                            T = U + ((1+1/max(imp))*B), 
                            LCL = Q - 1.96*sqrt(T), 
                            UCL = Q + 1.96*sqrt(T),
                            SE = sqrt(T)) 
p3est$race <- word(p3est$group, 1)
p3est$gender <- word(p3est$group, 2)
p3est$instruction <- word(p3est$group, 3)
p3est$race_gender <- paste(p3est$race,p3est$gender, sep= " ")
return <- p3est}
```

mod_pre_1 <- pre_score~1 + gend_URM*(asian_no_int + black_no_int + hispanic_no_int + race_other_no_int  + pacisland_no_int) + (1|course_id)

```{r}
#     c(I, F, A,B,H,O)
WMA = c(1, 0, 0,0,0,0)
AMA = c(1, 0, 1,0,0,0)
BMA = c(1, 0, 0,1,0,0)
HMA = c(1, 0, 0,0,1,0)
OMA = c(1, 0, 0,0,0,1)
WFA = c(1, 1, 0,0,0,0)
AFA = c(1, 1, 1,0,0,0)
BFA = c(1, 1, 0,1,0,0)
HFA = c(1, 1, 0,0,1,0)
OFA = c(1, 1, 0,0,0,1)

cf_e_pre_6 <- rbind('White Male Algebra'=WMA,  
                          'White Female Algebra'=WFA,
                          'Black Male Algebra'=BMA,  
                          'Black Female Algebra'=BFA,
                          'Asian Male Algebra'=AMA, 
                          'Asian Female Algebra'=AFA,
                          'Hispanic Male Algebra'=HMA, 
                          'Hispanic Female Algebra'=HFA,
                          'Other Male Algebra'=OMA,  
                          'Other Female Algebra'=OFA)

contrast_pre6_est <- pool_and_cov_diffwm(e_pre6,cf_e_pre_6)
unique(contrast_pre6_est$race)

contrast_pre6_est$race <- factor(contrast_pre6_est$race, levels = c("Black", "Hispanic", "Other", "Asian",    "White"))

ggplot(data=contrast_pre6_est, aes(x=race, y=Q, group=gender, color=gender)) + geom_point(position = position_dodge(width=0.90)) + geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  theme(legend.position = "right",  axis.text.x=element_text(angle=90) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("Pretest (%)") +
  scale_color_manual(name="Gender",
                     breaks= c("Female","Male"),
                     values=cbbpalette) +
  ylim(c(40,70))


#ggsave("~pre7.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
#kable(contrast_p7_est[c(1,2,6,7)], digits = 2)
```

```{r}
#     c(I, F, A,B,H,O, a,b,h,o)
WMA = c(1, 0, 0,0,0,0, 0,0,0,0)
AMA = c(1, 0, 1,0,0,0, 0,0,0,0)
BMA = c(1, 0, 0,1,0,0, 0,0,0,0)
HMA = c(1, 0, 0,0,1,0, 0,0,0,0)
OMA = c(1, 0, 0,0,0,1, 0,0,0,0)
WFA = c(1, 1, 0,0,0,0, 0,0,0,0)
AFA = c(1, 1, 1,0,0,0, 1,0,0,0)
BFA = c(1, 1, 0,1,0,0, 0,1,0,0)
HFA = c(1, 1, 0,0,1,0, 0,0,1,0)
OFA = c(1, 1, 0,0,0,1, 0,0,0,1)

cf_e_pre_7 <- rbind('White Male Algebra'=WMA,  
                          'White Female Algebra'=WFA,
                          'Black Male Algebra'=BMA,  
                          'Black Female Algebra'=BFA,
                          'Asian Male Algebra'=AMA, 
                          'Asian Female Algebra'=AFA,
                          'Hispanic Male Algebra'=HMA, 
                          'Hispanic Female Algebra'=HFA,
                          'Other Male Algebra'=OMA,  
                          'Other Female Algebra'=OFA)

contrast_p7_est <- pool_and_cov_diffwm(e_pre7,cf_e_pre_7)
unique(contrast_p7_est$race)

contrast_p7_est$race <- factor(contrast_p7_est$race, levels = c("Black", "Hispanic", "Other", "Asian",    "White"))

ggplot(data=contrast_p7_est, aes(x=race, y=Q, group=gender, color=gender)) + geom_point(position = position_dodge(width=0.90)) + geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  theme(legend.position = "right",  axis.text.x=element_text(angle=90) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("Pretest (%)") +
  scale_color_manual(name="Gender",
                     breaks= c("Female","Male"),
                     values=cbbpalette) 

#ggsave("~pre7.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
kable(contrast_p7_est[c(1,2,6,7)], digits = 2)
```

Posttest models

```{r}
e_post1 <- with(MIdata,{lmer(e_post~1 + (1|course_id))})
aic.1 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1 + (1|course_id))
  return <- AIC(mod_aic)
}

e_post2 <- with(MIdata,{lmer(e_post~1  + (1|course_id))})
aic.2 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1 + (1|course_id))
  return <- AIC(mod_aic)
}

e_post3 <- with(MIdata,{lmer(e_post~1  + female + (1|course_id))})
aic.3 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1  + female + (1|course_id))
  return <- AIC(mod_aic)
}

e_post4 <- with(MIdata,{lmer(e_post~1  + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))})
aic.4 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1 + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}


e_post5 <- with(MIdata,{lmer(e_post~1  + collab_learning_during_class +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))})
aic.5 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1  + collab_learning_during_class +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}

e_post6 <- with(MIdata,{lmer(e_post~1  +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))})
aic.6 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1 +  female + (asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}

e_post7 <- with(MIdata,{lmer(e_post~1  + female*(asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) + (1|course_id) )})
aic.7 <- foreach(i=1:10, .combine=rbind) %do% {
  mod_aic <- lmer(data=MIdata[[i]], e_post~1  + collab_learning_during_class +  female*(asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) +(1|course_id))
  return <- AIC(mod_aic)
}

e_post8 <- with(MIdata,{lmer(e_post~1  + e_pre + female*(asian_no_int + black_no_int + hispanic_no_int + race_otherstar_no_int) + (1|course_id) )})

info_crit <- as.data.frame(cbind(aic.1,aic.2,aic.3,aic.4,aic.5,aic.6,aic.7))
#info_crit[11,] <- colMeans(info_crit)

colnames(info_crit) <- c("aic.1", "aic.2","aic.3","aic.4","aic.5","aic.6","aic.7")

ics <- as.data.frame(colMeans(info_crit))
ics$delta <- ics$`colMeans(info_crit)`- min(ics$`colMeans(info_crit)`)

barplot(ics$delta)

testEstimates(e_post1, var.comp=TRUE)
testEstimates(e_post2, var.comp=TRUE)
testEstimates(e_post3, var.comp=TRUE)
testEstimates(e_post4, var.comp=TRUE)
testEstimates(e_post5, var.comp=TRUE) 
testEstimates(e_post6, var.comp=TRUE)
testEstimates(e_post7, var.comp=TRUE)
```


```{r}
#     c(I, F, A,B,H,O)
WMA = c(1, 0, 0,0,0,0)
AMA = c(1, 0, 1,0,0,0)
BMA = c(1, 0, 0,1,0,0)
HMA = c(1, 0, 0,0,1,0)
OMA = c(1, 0, 0,0,0,1)
WFA = c(1, 1, 0,0,0,0)
AFA = c(1, 1, 1,0,0,0)
BFA = c(1, 1, 0,1,0,0)
HFA = c(1, 1, 0,0,1,0)
OFA = c(1, 1, 0,0,0,1)

cf_e_post_6 <- rbind('White Male Algebra'=WMA,  
                          'White Female Algebra'=WFA,
                          'Black Male Algebra'=BMA,  
                          'Black Female Algebra'=BFA,
                          'Asian Male Algebra'=AMA, 
                          'Asian Female Algebra'=AFA,
                          'Hispanic Male Algebra'=HMA, 
                          'Hispanic Female Algebra'=HFA,
                          'Other Male Algebra'=OMA,  
                          'Other Female Algebra'=OFA)

contrast_post6_est <- pool_and_cov_diffwm(e_post6,cf_e_post_6)
unique(contrast_post6_est$race)

contrast_post6_est$race <- factor(contrast_post6_est$race, levels = c("Black", "Hispanic", "Other", "Asian",    "White"))

ggplot(data=contrast_post6_est, aes(x=race, y=Q, group=gender, color=gender)) + geom_point(position = position_dodge(width=0.90)) + geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  theme(legend.position = "right",  axis.text.x=element_text(angle=90) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("posttest (%)") +
  scale_color_manual(name="Gender",
                     breaks= c("Female","Male"),
                     values=cbbpalette)

#ggsave("~post7.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
kable(contrast_p7_est[c(1,2,6,7)], digits = 2)
```

```{r}
#     c(I, F, A,B,H,O, a,b,h,o)
WMA = c(1, 0, 0,0,0,0, 0,0,0,0)
AMA = c(1, 0, 1,0,0,0, 0,0,0,0)
BMA = c(1, 0, 0,1,0,0, 0,0,0,0)
HMA = c(1, 0, 0,0,1,0, 0,0,0,0)
OMA = c(1, 0, 0,0,0,1, 0,0,0,0)
WFA = c(1, 1, 0,0,0,0, 0,0,0,0)
AFA = c(1, 1, 1,0,0,0, 1,0,0,0)
BFA = c(1, 1, 0,1,0,0, 0,1,0,0)
HFA = c(1, 1, 0,0,1,0, 0,0,1,0)
OFA = c(1, 1, 0,0,0,1, 0,0,0,1)

cf_e_post_7 <- rbind('White Male Algebra'=WMA,  
                          'White Female Algebra'=WFA,
                          'Black Male Algebra'=BMA,  
                          'Black Female Algebra'=BFA,
                          'Asian Male Algebra'=AMA, 
                          'Asian Female Algebra'=AFA,
                          'Hispanic Male Algebra'=HMA, 
                          'Hispanic Female Algebra'=HFA,
                          'Other Male Algebra'=OMA,  
                          'Other Female Algebra'=OFA)

contrast_p7_est <- pool_and_cov_diffwm(e_post7,cf_e_post_7)
unique(contrast_p7_est$race)

contrast_p7_est$race <- factor(contrast_p7_est$race, levels = c("Black", "Hispanic", "Other", "Asian",    "White"))

ggplot(data=contrast_p7_est, aes(x=race, y=Q, group=gender, color=gender)) + geom_point(position = position_dodge(width=0.90)) + geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  theme(legend.position = "right",  axis.text.x=element_text(angle=90) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("posttest (%)") +
  scale_color_manual(name="Gender",
                     breaks= c("Female","Male"),
                     values=cbbpalette) 

#ggsave("~post7.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
kable(contrast_p7_est[c(1,2,6,7)], digits = 2)
```

```{r}
contrast_post6_est$time <- "Post"
contrast_pre6_est$time <- "Pre"
for_plot <- rbind(contrast_post6_est,contrast_pre6_est)
for_plot$Time <- factor(for_plot$time, levels=c("Pre","Post")) 
for_plot$gender_time <- paste(for_plot$Time, for_plot$gender)
for_plot$gender_time <- factor(for_plot$gender_time, levels=c("Pre Female","Pre Male","Post Female","Post Male"))

ggplot(data=for_plot, aes(x=race, y=Q, group=gender_time, color=gender, shape=Time)) + geom_point(position = position_dodge(width=0.90), size=2) + geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  theme( axis.text.x=element_text(angle=90) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("Expert-like Score (%)") +
  scale_color_manual(name="Gender",
                     breaks= c("Female","Male"),
                     values=cbbpalette) 
ggsave("PERC_narrow.png", plot= last_plot(), dpi=300, width = 3.5, height = 4.5, units = "in", device = "png")
ggsave("PERC_wide.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```
Model construction
```{r}
  
models <- c("e_pre1","e_pre3","e_pre4","e_pre6")
mod_var_tab <- data_frame(model = NA,
                          level2 = NA,
                          level1 = NA,
                          ICC = NA)
for(i in 1:4){
  temp <- testEstimates(get(models[i]), var.comp=TRUE)
  mod_var_tab[i,1] <- models[i]
  mod_var_tab[i,2] <- temp$var.comp[1]
  mod_var_tab[i,3] <- temp$var.comp[2]
  mod_var_tab[i,4] <- temp$var.comp[3]
  }
mod_var_tab$lvl1change <- (mod_var_tab$level1[1]- mod_var_tab$level1)/mod_var_tab$level1[1]
mod_var_tab$lvl2change <- (mod_var_tab$level2[1]- mod_var_tab$level2)/mod_var_tab$level2[1]

temp_mod <- mod_var_tab

models <- c("e_post1","e_post3","e_post4","e_post6","e_post8")
mod_var_tab <- data_frame(model = NA,
                          level2 = NA,
                          level1 = NA,
                          ICC = NA)
for(i in 1:5){
  temp <- testEstimates(get(models[i]), var.comp=TRUE)
  mod_var_tab[i,1] <- models[i]
  mod_var_tab[i,2] <- temp$var.comp[1]
  mod_var_tab[i,3] <- temp$var.comp[2]
  mod_var_tab[i,4] <- temp$var.comp[3]
  }
mod_var_tab$lvl1change <- (mod_var_tab$level1[1]- mod_var_tab$level1)/mod_var_tab$level1[1]
mod_var_tab$lvl2change <- (mod_var_tab$level2[1]- mod_var_tab$level2)/mod_var_tab$level2[1]

temp2 <- rbind(temp_mod, mod_var_tab)



#mod_var_tab$equation <- c("gain~1 + (1|course_id)","gain~1 + stud_pre_cent + (1|course_id))","gain~1 + stud_pre_cent + retake + (1|course_id)","gain~1 + stud_pre_cent + retake + FMCE + (1|course_id)","gain~1 + stud_pre_cent + retake + FMCE + (1|course_id)","gain~1 + stud_pre_cent + retake + gend_URM + (1|course_id)", "gain~1 + stud_pre_cent + retake + gend_URM + asian_no_int + black_no_int + hispanic_no_int + race_other_no_int + (1|course_id)","gain~1 + stud_pre_cent + retake + gend_URM + asian_no_int + black_no_int + hispanic_no_int + race_other_no_int + lec + (1|course_id)","gain~1 + stud_pre_cent + retake + gend_URM*(asian_no_int + black_no_int + hispanic_no_int + race_other_no_int) + lec + (1|course_id)","gain~1 + stud_pre_cent + retake + asian_no_int + black_no_int + hispanic_no_int + race_other_no_int + gend_URM*lec +  (1|course_id)","gain~1 + lec*(asian_no_int + black_no_int + hispanic_no_int + race_other_no_int) + gend_URM + stud_pre_cent + retake + (1|course_id)")
#"gain~1 + stud_pre_cent + retake + gend_URM + asian_no_int + black_no_int + hispanic_no_int + race_other_no_int + lec + (1 + stud_pre_cent + gend_URM + asian_no_int + black_no_int + hispanic_no_int + race_other_no_int |course_id)"
```

```{r}
#variables: M, group by

desc2 <- foreach(i=1:10, .combine=rbind) %do% {
temp <- MIdata[[i]]
temp$race <- ifelse(temp$black_no_int ==1, "Black",ifelse(temp$hispanic_no_int ==1, "Hispanic",ifelse(temp$asian_no_int ==1, "Asian",ifelse(temp$race_otherstar_no_int ==1, "Other","White"))))
desc <- temp %>% group_by(race, male) %>% summarise(N = length(e_pre),
                                                                 pre_mean = mean(e_pre),
                                                                 pre_sd = sd(e_pre),
                                                                 post_mean = mean(e_post),
                                                                 post_sd = sd(e_post),
                                                                 gain_mean = mean (e_post-e_pre),
                                                                 gain_sd = sd(e_post-e_pre)
                                                                 )


return <- desc
}
desc <- desc2 %>% group_by(race, male) %>% summarise_all(funs(mean))
#desc$collab_learning_during_class <- ifelse(desc$collab_learning_during_class ==0, "Lecture","Collaborative")
desc$male <- ifelse(desc$male==0, "Female","Male")
kable(desc, digits=1)
#sum(temp$hispanic_no_int)
#length(temp[temp$his])

```

